### ISSUE TITLE
Recipe Removal Auto Complete Issue

### ISSUE THREAD

**Issue by Darkosto** [way2muchnoise/ZenScript-Highlighter#11]
Heya Way,

Is there any way you could edit the auto-complete for "recipes.remove(, );" and remove the comma? Most removal recipes won't need that extra comma :)

Thank you!
Darkosto

**Comment by way2muchnoise** [comment]
Just dumping a link that is kinda related to this :p

https://github.com/jaredlll08/RecipeStages/blob/master/src/main/java/com/blamejared/recipestages/handlers/Recipes.java

**Comment by way2muchnoise** [comment]
@Darkosto is this still an issue?

**Comment by way2muchnoise** [comment]
Closing due to unresponsive and thus assumed fixed.
