### ISSUE TITLE
Relational Operators are flagged red in highlighter

### ISSUE THREAD

**Issue by Vyraal1** [way2muchnoise/ZenScript-Highlighter#13]
Using the example script here: https://gist.github.com/kindlich/9840f695dce5a4b78f78599ff6c1232c in lines 113 and 122, the use of the relational operators seems to mark them red falsely, most likely thinking it's an IItemStack.

**Comment by way2muchnoise** [comment]
Could you add a screenshot of what you mean?

**Comment by Vyraal1** [comment]
https://imgur.com/a/Vdptn

**Comment by way2muchnoise** [comment]
fixed in 4d4f6c28ddcd9c29950409e37505a5bf29389132
