### ISSUE TITLE
Less than and Greater than relational operators used in statements break formatting. 

### ISSUE THREAD

**Issue by Rosethorns** [way2muchnoise/ZenScript-Highlighter#20]
Formatting assumes the use of a < or > as brackets and any following code formatting breaks.
![image](https://user-images.githubusercontent.com/2171914/48307429-4ededa80-e5b1-11e8-8a70-fc34d85ed288.png)

**Comment by way2muchnoise** [comment]
fixed in 4d4f6c28ddcd9c29950409e37505a5bf29389132
