### ISSUE TITLE
word "let"

### ISSUE THREAD

**Issue by Alexey-T** [way2muchnoise/ZenScript-Highlighter#3]
Why not hilited "let" in ex1.zs:
~~~
id2(x1) =>

   id(x2) => (x2, x2)

   let id3 : Product<A> -> Product<A, A> = (x3) => id(

      x3)

   id4(x : Int) => x

   let y = id(id4(x1))

   return id3(((x4) => x4)(y))

id2(42)
~~~
file from GH

**Comment by way2muchnoise** [comment]
I'm pretty we aren't talking about the same ZenScript. This highlighting is made for the [ZenScript made for MineTweaker/CraftTweaker/ModTweaker](https://github.com/stanhebben/MineTweaker3/tree/master/ZenScript). But I can add the keyword let if you really need it :D

**Comment by Alexey-T** [comment]
This is same ZenScript? https://github.com/keean/zenscript/blob/master/examples/ex1.zs

**Comment by way2muchnoise** [comment]
Nope, different ZenScript. Guess you'll have to keep looking to find one for that specific zenscript :(
