### ISSUE TITLE
Dots messing syntax highlight.

### ISSUE THREAD

**Issue by JasonMcRay** [way2muchnoise/ZenScript-Highlighter#7]
![image](https://cloud.githubusercontent.com/assets/4236895/23663145/00ee3a5c-0352-11e7-95c1-8a5678a29866.png)

In this script I am getting that the ending ] is invalid. I have found out that it is because of the dots in xxx.definition.makeStack(i). Is it possible to have a fix?

If i put it all in one line, it still happens

**Comment by JasonMcRay** [comment]
From the looks it is the same issue as #1

**Comment by way2muchnoise** [comment]
I see, this is happening with vars?

**Comment by JasonMcRay** [comment]
Yep looks like it. When i change the `plankTreatedWood `to `<immersiveengineering:treatedWood>` it does highlight the end ] as invalid

**Comment by way2muchnoise** [comment]
I'll see what I can do about it :D mind sharing that script or a snippet of it? Makes it easier to test against (also I'm lazy :p)

**Comment by JasonMcRay** [comment]
https://gist.github.com/JasonMcRay/15e29ca63206b6d75a51c18b8645f2df - Work in progress :)
